### ISSUE TITLE
Propellant Wishlist

### ISSUE THREAD

**Issue by ferram4** [ferram4/ProcEngines#1]
The options that this project are based on how many propellant mixtures we have to work with.  If you'd like to help, please check out [the WIP propellant config tutorial](https://github.com/ferram4/ProcEngines/wiki/Adding-A-New-Bipropellant-Mixture-(WIP)).

**If there is something you're interested in working on, please comment.  These configs are a lot of work and I would like to avoid duplicating work if possible.**  Once you begin work on a mixture config, please make an issue for that mixture and link it below, so that things can be organized well.

---

So far we have 3 necessary configs that need to be completed:
- [x] RP-1 + LOX (complete due to #8)
- [x] LH2 + LOX (complete due to #4)
- [x] UDMH + NTO (complete due to #7)

With these completed we will be able to create a reasonable simile of every in-common use engine that has flown.

---

There are several uncommon propellant combos that we can use that aren't in common use that would also be nice that the above 3 combos can not stand in for.  They are, in order of desirability:

- [x] Methane + LOX (closed by #10)
- [ ] RP-1 + H2O2 (97% H2O2 in RF; use 2:1 of 98% to 95% in RPA)
- [ ] Ethanol + LOX
- [ ] Hydyne + LOX
- [ ] RP-1 + Nitric Acid

---

There are several other combos (mostly hypergolics) that would be nice to have but are sufficiently similar to UDMH + NTO that I won't list them here as they aren't a priority.  If you've got some weird love for one of them, I'll still accept the configs, but there are higher priorities.

**Comment by Tyaedalis** [comment]
I'll take on LH2 + LOX, and possibly more.

I wrote a quick little Python script to extract relevant data from text files generated by RPA: 
```
from os import walk

files = []
for (dirpath, dirnames, filenames) in walk('./data/'):
    files.extend(filenames)
    break

data = []
OFratio = None
for file in files:
    t = []
    with open('./data/' + file) as f:
        for i, line in enumerate(f):
            if i in [15, 24, 25, 31, 34, 39]:
                t.append(line.split())

    OFratio = t[0][2]
    Pc = t[1][1]
    Tc = t[2][1]
    Te = t[2][4]
    Pe = t[1][4]
    MW = t[4][4]
    gamma = t[3][4]
    Mach = t[5][5]

    data.append([Pc, Tc, Te, Pe, MW, gamma, Mach])

if len(data) < 15:
    print('[WRN] Less than 15 keys!')

block = ''.join(['MixtureRatioData\n{\n  OFratio =', OFratio,
        '\n  PressureData\n  {\n',
        ''.join(['    key = {}, {}, {}, {}, {}, {}, {}\n'.format(*line) for line in data]),
        '  }\n}'])

with open('results.txt', 'a') as f:
    f.write(block)
```

It assumes you are saving the generated text files in the same directory as the script, named `data.txt`. It will append `results.txt` with a new line each time it is run. Only run it once per set of data.

***There is an up-to-date version of this script and more info in issue #3!***

**Comment by ferram4** [comment]
If you'd like to get started with LH2 + LOX, go ahead; the extra instructions for handling rich mixtures doesn't apply for LH2 + LOX given the lack of carbon.  Also, thanks!

**Comment by Tyaedalis** [comment]
Ah, thanks. I was wondering why I kept getting weird data. It seems LH2/LOX has a huge range of operable ratios, from 1-204 by my guess. Does that seem correct to you?

Happy to help. I've been wanting procedural engines for some time!

**Comment by ferram4** [comment]
I'd go for lower O/F ratios, actually.  Hydrolox engines tend to run really fuel-rich, and their preburners/gas generators even more so, so I'd take the O/F down to 0.1 at least.  Maybe a little lower.  As for the high end, 204 is probably a little extreme; I believe the numbers, but I know that no engine has ever run that O/F at any condition, so you can probably pick a lower range to start off with.

Tell you what, start by going up to ~20, and if needed we can fill in the higher range later and limit hydrolox to fuel-rich only.  Your optimal range should be from ~4-6, and the performance should be nice and smooth through there.

Go make an issue for adding hydrolox and link it here; I'll add a note to the top that when someone starts work on a mixture they should make a new issue and link it here, so that I can link to it in the OP in case others want to help and for specific discussions of pressure ranges, O/Fs, etc.

**Comment by ferram4** [comment]
@Tyaedalis Hey, I hate to bug you after all you've done, but I think I'll need an extra pair of value for these configs.  It turns out that the specific heat capacity calculated by RPA is significantly different (like, >100% error in some cases O_o) than the one I calculate using the ideal gas laws and what's already in the configs.

If you have the time and willingness, could you go and re-run the sims and append Specific Heat (const=p) entries from the "injector" and "nozzle exit" columns to each of the PressureMixtureData keys?

**Comment by Tyaedalis** [comment]
I should have kept all the data! I'll work on it.

**Comment by dgeastman** [comment]
I'm working on [methalox](https://github.com/ferram4/ProcEngines/issues/9).
